### ISSUE TITLE
Update comments in main re: when which optimizations are run

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#256]
The main function says things like
```
    // we run the optimization passes inside miri
    // if we ran them twice we'd get funny failures due to borrowck ElaborateDrops only working on
    // unoptimized MIR
    // FIXME: add an after-mir-passes hook to rustc driver
    args.push("-Zmir-opt-level=0".to_owned());
```
I tried to find *where* these optimization passes are run, and couldn't. @eddyb when asked said the comment is outdated. However, if I remove the `args.push`, the test suite fails -- so something is clearly still going on.

I would appreciate if someone who knew what is happening could expand/update the comment -- or explain things to me and then I will update the comment. ;)

**Comment by solson** [comment]
It could just be a latent Miri bug if the test suite fails when optimizations are enabled. I'm not sure what the situation with the comment becoming out of date is. I would try to search the git history for code related to "mir", "pass", and "run". It was named something along those lines...

**Comment by oli-obk** [comment]
We used to actually run the optimizations by hand. I thought that was removed entirely. Only cfail  tests should break. Everything else is a bug

**Comment by oli-obk** [comment]
Related: https://github.com/solson/miri/commit/07229d6305bbfc132b144d0974042eff9fb015ee

**Comment by RalfJung** [comment]
Here are some of the failures I get when removing the "disable optimizations" line:

```
---- [mir-opt] mir-opt/tuple_like_enum_variant_constructor_struct_pointer_opt.rs stdout ----

error: compilation failed!
status: exit code: 101
command: target/debug/miri tests/run-pass/tuple_like_enum_variant_constructor_struct_pointer_opt.rs -L /tmp --target=x86_64-unknown-linux-gnu -Z dump-mir=all -Z mir-opt-level=3 -Z dump-mir-dir=/tmp/tuple_like_enum_variant_constructor_struct_pointer_opt -L /tmp/tuple_like_enum_variant_constructor_struct_pointer_opt.stage-id.mir-opt.libaux -C prefer-dynamic -o /tmp/tuple_like_enum_variant_constructor_struct_pointer_opt.stage-id
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /home/r/src/rust/miri/src/step.rs:106: SetDiscriminant on std::option::Option<A> represented as StructWrappedNullablePointer {
    nndiscr: 1,
    nonnull: Struct {
        align: Align {
            abi: 3,
            pref: 3
        },
        primitive_align: Align {
            abi: 3,
            pref: 3
        },
        packed: false,
        sized: true,
        offsets: [
            Size {
                raw: 0
            }
        ],
        memory_index: [
            0
        ],
        min_size: Size {
            raw: 16
        }
    },
    discrfield: [
        0,
        0,
        1
    ],
    discrfield_source: [
        0,
        0,
        1
    ]
}

thread 'main' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:489:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
---- [mir-opt] mir-opt/tuple_like_enum_variant_constructor_pointer_opt.rs stdout ----

error: compilation failed!
status: exit code: 101
command: target/debug/miri tests/run-pass/tuple_like_enum_variant_constructor_pointer_opt.rs -L /tmp --target=x86_64-unknown-linux-gnu -Z dump-mir=all -Z mir-opt-level=3 -Z dump-mir-dir=/tmp/tuple_like_enum_variant_constructor_pointer_opt -L /tmp/tuple_like_enum_variant_constructor_pointer_opt.stage-id.mir-opt.libaux -C prefer-dynamic -o /tmp/tuple_like_enum_variant_constructor_pointer_opt.stage-id
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /home/r/src/rust/miri/src/lvalue.rs:84: to_ptr_and_extra: expected Lvalue::Ptr, got Local { frame: 0, local: _9 }

thread 'main' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:489:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
```
---- [mir-opt] mir-opt/strings.rs stdout ----

error: compilation failed!
status: exit code: 101
command: target/debug/miri tests/run-pass/strings.rs -L /tmp --target=x86_64-unknown-linux-gnu -Z dump-mir=all -Z mir-opt-level=3 -Z dump-mir-dir=/tmp/strings -L /tmp/strings.stage-id.mir-opt.libaux -C prefer-dynamic -o /tmp/strings.stage-id
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /home/r/src/rust/miri/src/lvalue.rs:84: to_ptr_and_extra: expected Lvalue::Ptr, got Local { frame: 1, local: _2 }

thread 'main' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:489:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

------------------------------------------

thread '[mir-opt] mir-opt/strings.rs' panicked at 'explicit panic', /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.2.8/src/runtest.rs:2374:8
```
I just assumed this would show that the command is still needed. But maybe these are just miri bugs that only surface when certain optimizations run?

**Comment by RalfJung** [comment]
I can reproduce the bug outside the test harness:
```
cargo run --bin miri -- -Zmir-opt-level=3 tests/run-pass/strings.rs
```

**Comment by oli-obk** [comment]
Jup these are bugs. I even remember these exact errors, but I think there used to be more, which is good

**Comment by oli-obk** [comment]
I had to disable a test that was failing due to https://github.com/rust-lang/rust/issues/43358 (also fails if actually compiled and run with mir optimizations, so it's not our fault)
